# Setup
name:         物聯智慧雲服務
tagline:      智慧物聯雲服務網站(Thingsboard ，Arduino, Raspberry Pi, LoRa)
baseurl:      "/SmartIoTCloud"
locale:       "zh-hant"

# Gems
plugins:
  - jekyll-paginate

#Others
markdown: kramdown

# kramdown:
#   syntax_highlighter: pygments

highlighter: pygments
