# Setup
name:         物聯智慧雲服務
tagline:      物聯智慧雲服務網站(Thingsboard ，Arduino, Raspberry Pi, LoRa)
baseurl:      "/SmartIoTCloud"
locale:       "zh-hant"

permalink: /:year/:month/:day/:title:output_ext

# Gems
plugins:
  - jekyll-paginate

#Others
markdown: kramdown
timezone: Asia/Taipei

kramdown:
  syntax_highlighter_opts:
    disable: true


highlighter: none
